apiVersion: apps/v1
kind: Deployment
metadata:
  name: licence-deployment
  labels:
    app: licence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: licence
  template:
    metadata:
      labels:
        app: licence
    spec:
      containers:
        - name: licence
          image: sara4cristina/licence:0.0.6-SNAPSHOT
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: licence-service
spec:
  selector:
    app: licence
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
