apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchase-deployment
  labels:
    app: purchase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: purchase
  template:
    metadata:
      labels:
        app: purchase
    spec:
      containers:
        - name: purchase
          image: sara4cristina/purchase:0.0.8-SNAPSHOT
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: purchase-service
spec:
  selector:
    app: purchase
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
